// Generated by scripts/generate-database-types.mts from the cumulative migrations.
// Do not edit this file directly. Run npm run db:types.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      deliveries: {
        Row: {
          id: string;
          job_id: string;
          description: string;
          file_urls: Json;
          submitted_by: string;
          submitted_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          description: string;
          file_urls?: Json;
          submitted_by: string;
          submitted_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          description?: string;
          file_urls?: Json;
          submitted_by?: string;
          submitted_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deliveries_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      disputes: {
        Row: {
          id: string;
          job_id: string;
          raised_by: string;
          contested_term: string;
          claim_description: string;
          evidence_urls: Json;
          response_from_other_party: string | null;
          dispute_status: string;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          raised_by: string;
          contested_term: string;
          claim_description: string;
          evidence_urls?: Json;
          response_from_other_party?: string | null;
          dispute_status?: string;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          raised_by?: string;
          contested_term?: string;
          claim_description?: string;
          evidence_urls?: Json;
          response_from_other_party?: string | null;
          dispute_status?: string;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "disputes_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      evidence_files: {
        Row: {
          id: string;
          job_id: string;
          storage_path: string;
          filename: string;
          content_type: string;
          size_bytes: number;
          uploaded_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          storage_path: string;
          filename: string;
          content_type: string;
          size_bytes: number;
          uploaded_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          storage_path?: string;
          filename?: string;
          content_type?: string;
          size_bytes?: number;
          uploaded_by?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evidence_files_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      job_participants: {
        Row: {
          id: string;
          job_id: string;
          role: string;
          user_id: string | null;
          display_name: string | null;
          email: string | null;
          phone: string | null;
          detail_status: string;
          action_token_hash: string | null;
          token_expires_at: string | null;
          token_used: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          role: string;
          user_id?: string | null;
          display_name?: string | null;
          email?: string | null;
          phone?: string | null;
          detail_status?: string;
          action_token_hash?: string | null;
          token_expires_at?: string | null;
          token_used?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          role?: string;
          user_id?: string | null;
          display_name?: string | null;
          email?: string | null;
          phone?: string | null;
          detail_status?: string;
          action_token_hash?: string | null;
          token_expires_at?: string | null;
          token_used?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "job_participants_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "job_participants_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          }
        ];
      };
      job_terms: {
        Row: {
          id: string;
          job_id: string;
          service: string;
          service_category: string;
          scope: string;
          deliverables: Json;
          price: number;
          currency: string;
          deadline: string;
          revisions_included: number;
          revisions_used: number;
          cancellation_terms: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          service: string;
          service_category: string;
          scope: string;
          deliverables?: Json;
          price: number;
          currency?: string;
          deadline: string;
          revisions_included?: number;
          revisions_used?: number;
          cancellation_terms: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          service?: string;
          service_category?: string;
          scope?: string;
          deliverables?: Json;
          price?: number;
          currency?: string;
          deadline?: string;
          revisions_included?: number;
          revisions_used?: number;
          cancellation_terms?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "job_terms_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: true;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      jobs: {
        Row: {
          id: string;
          public_id: string;
          provider_id: string;
          status: string;
          source_channel: string;
          provider_location: string;
          client_location: string | null;
          first_viewed_at: string | null;
          last_viewed_at: string | null;
          view_count: number;
          created_at: string;
          updated_at: string;
          version: number;
          repeat_use: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          public_id: string;
          provider_id: string;
          status?: string;
          source_channel?: string;
          provider_location: string;
          client_location?: string | null;
          first_viewed_at?: string | null;
          last_viewed_at?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          version?: number;
          repeat_use?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          provider_id?: string;
          status?: string;
          source_channel?: string;
          provider_location?: string;
          client_location?: string | null;
          first_viewed_at?: string | null;
          last_viewed_at?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          version?: number;
          repeat_use?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "jobs_provider_fk";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          }
        ];
      };
      payments: {
        Row: {
          id: string;
          job_id: string;
          payment_mode: string;
          reference: string | null;
          notes: string | null;
          recorded_by: string;
          verification_status: string;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          payment_mode?: string;
          reference?: string | null;
          notes?: string | null;
          recorded_by?: string;
          verification_status?: string;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          payment_mode?: string;
          reference?: string | null;
          notes?: string | null;
          recorded_by?: string;
          verification_status?: string;
          recorded_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: true;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      profiles: {
        Row: {
          id: string;
          user_id: string | null;
          username: string;
          display_name: string;
          avatar_url: string | null;
          country: string;
          state: string | null;
          city: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          username: string;
          display_name: string;
          avatar_url?: string | null;
          country?: string;
          state?: string | null;
          city?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          username?: string;
          display_name?: string;
          avatar_url?: string | null;
          country?: string;
          state?: string | null;
          city?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_auth_user_fk";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      provider_profiles: {
        Row: {
          id: string;
          user_id: string;
          headline: string;
          bio: string | null;
          service_area: string;
          verification_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          headline: string;
          bio?: string | null;
          service_area: string;
          verification_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          headline?: string;
          bio?: string | null;
          service_area?: string;
          verification_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          }
        ];
      };
      reviews: {
        Row: {
          id: string;
          job_id: string;
          reviewer_id: string;
          reviewer_name: string;
          rating: number;
          comment: string | null;
          submitted_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          reviewer_id: string;
          reviewer_name: string;
          rating: number;
          comment?: string | null;
          submitted_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          reviewer_id?: string;
          reviewer_name?: string;
          rating?: number;
          comment?: string | null;
          submitted_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: true;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      revisions: {
        Row: {
          id: string;
          job_id: string;
          revision_number: number;
          description: string;
          requested_by: string;
          requested_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          revision_number: number;
          description: string;
          requested_by?: string;
          requested_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          revision_number?: number;
          description?: string;
          requested_by?: string;
          requested_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "revisions_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
      trust_events: {
        Row: {
          id: string;
          job_id: string;
          actor_id: string;
          actor_type: string;
          event_type: string;
          occurred_at: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          actor_id: string;
          actor_type: string;
          event_type: string;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          actor_id?: string;
          actor_type?: string;
          event_type?: string;
          occurred_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "trust_events_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      public_job_records: {
        Row: {
          public_id: string | null;
          status: string | null;
          source_channel: string | null;
          provider_location: string | null;
          created_at: string | null;
          first_viewed_at: string | null;
          service: string | null;
          service_category: string | null;
          scope: string | null;
          deliverables: Json | null;
          price: number | null;
          currency: string | null;
          deadline: string | null;
          revisions_included: number | null;
          revisions_used: number | null;
          cancellation_terms: string | null;
          provider_username: string | null;
          provider_name: string | null;
          provider_avatar: string | null;
          provider_role: string | null;
          provider_verification_status: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      tl_assert_job_participants: {
        Args: {
          p_job_id: string | null;
        };
        Returns: undefined;
      };
      tl_commit_job: {
        Args: {
          p_record: Json | null;
          p_expected_version: number | null;
        };
        Returns: undefined;
      };
      tl_read_job: {
        Args: {
          p_id: string | null;
          p_public: boolean | null;
        };
        Returns: Json;
      };
      tl_snake_keys: {
        Args: {
          value: Json | null;
        };
        Returns: Json;
      };
      tl_update_profile: {
        Args: {
          p_user_id: string | null;
          p_input: Json | null;
        };
        Returns: undefined;
      };
      uuid_generate_v4: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
