import Link from "next/link";
import { Navbar } from "@/components/navigation/navbar";
import { Footer } from "@/components/navigation/footer";
import { Button } from "@/components/ui/button";
import { Hero3DCard } from "@/components/home/hero-3d-card";
import { ConversationToRecord } from "@/components/home/whatsapp-reality-compare";
import { InteractiveDealSimulator } from "@/components/home/interactive-deal-simulator";
export const metadata={title:"TrustLink — Make the agreement clear",description:"Turn your service agreement into a clear transaction record: scope, fee, deadline, delivery and client approval."};
const steps=[["Agree","Discuss the work wherever you already talk."],["Record","Put the scope, fee and deadline in writing."],["Accept","Your client reviews and accepts the terms."],["Work","Record direct payment and start the work."],["Deliver","Submit work against the agreed scope."],["Complete","Resolve revisions, approve and close the record."]];
export default function Page() {
  return <><Navbar/><main id="main-content">
    <section className="bg-[#f3f2ee] border-b border-surface-200 py-14 sm:py-20 lg:py-24"><div className="shell grid lg:grid-cols-[1fr_1fr] gap-12 lg:gap-20 items-center">
      <div><p className="eyebrow">For work that starts with a conversation</p><h1 className="font-serif font-normal text-[2.8rem] sm:text-6xl xl:text-[4.25rem] leading-[1.07] tracking-tight my-6 max-w-xl">Meet anywhere.<br/>Agree clearly.<br/><span className="text-surface-500">Work confidently.</span></h1><p className="text-base sm:text-lg text-surface-600 leading-8 max-w-md">Turn your deal into one clear record. Scope, fee, deadline and delivery — agreed with your client, easy to return to.</p><div className="flex flex-wrap items-center gap-x-7 gap-y-4 mt-8"><Button href="/signup" size="lg">Create your first TrustLink</Button><Link href="/j/sample-website-project" className="text-sm underline underline-offset-4 py-3">View an example →</Link></div><p className="text-xs text-surface-500 mt-7">Your client opens a link. No app to install.</p></div>
      <Hero3DCard/>
    </div></section>
    <ConversationToRecord/>
    <section className="section bg-white"><div className="shell"><p className="eyebrow">How TrustLink works</p><h2 className="text-3xl sm:text-4xl mt-4 mb-12 max-w-xl">A record of what was agreed.<br/>And what happened next.</h2><ol className="grid md:grid-cols-3 lg:grid-cols-6">{steps.map(([verb,body],i)=><li key={verb} className="relative pl-7 pb-8 md:pl-0 md:pr-6 md:pt-5 border-l md:border-l-0 md:border-t border-surface-300"><span className="absolute -left-1 top-0 md:left-0 md:-top-1 h-2 w-2 rounded-full bg-navy-900" aria-hidden="true"/><p className="text-xs text-surface-500 mb-4">0{i+1}</p><h3 className="text-base font-semibold mb-3">{verb}</h3><p className="text-sm leading-6 text-surface-500">{body}</p></li>)}</ol></div></section>
    <InteractiveDealSimulator/>
    <section className="section bg-white"><div className="shell grid md:grid-cols-2 gap-12 lg:gap-24">{[
      ["For providers","Keep the scope clear from the start.","Record your terms before work begins. Deliver against them, keep revision requests together, and build a history of completed work.","/for-providers"],
      ["For businesses","Know what was agreed. Track what happened.","Review the deliverables, fee and deadline in one place. Accept the agreement, inspect delivery and raise a specific concern when needed.","/for-businesses"]
    ].map(([label,title,body,href])=><div key={href}><p className="eyebrow">{label}</p><h2 className="text-3xl mt-4 mb-5">{title}</h2><p className="text-surface-600 leading-7">{body}</p><Link href={href} className="inline-block text-sm underline underline-offset-4 mt-6 py-2">Read the overview →</Link></div>)}</div></section>
    <section className="section bg-surface-50 border-y"><div className="shell grid lg:grid-cols-2 gap-12 lg:gap-20 items-start"><div><p className="eyebrow">The Trust Profile</p><h2 className="text-3xl sm:text-4xl mt-4 mb-5">Reputation built from completed work.</h2><p className="text-surface-600 leading-7">Each completed transaction becomes part of a history clients can inspect. Reviews and delivery performance come from those records.</p><Link href="/p/amaka" className="inline-block mt-6 py-2 text-sm underline">Explore an example profile →</Link></div><div className="border-t-2 border-navy-900 pt-6"><p className="text-xs text-surface-500 mb-6">Example profile · Illustrative data</p><h3 className="text-2xl font-semibold">Amaka Okafor</h3><p className="text-sm text-surface-500 mt-2">Web designer & frontend developer · Lagos</p><div className="flex justify-between gap-4 py-6 border-y mt-6 text-sm"><div><p className="font-medium">Brand website refresh</p><p className="text-surface-500 text-xs mt-2">Example completed transaction · 18 Oct 2026</p></div><span>₦180,000</span></div><p className="text-xs leading-6 text-surface-500 mt-4">Provider details are self-provided. TrustLink does not independently verify identity or payments.</p></div></div></section>
    <section className="section bg-navy-900 text-white"><div className="shell flex flex-col md:flex-row items-start md:items-center justify-between gap-8"><div><p className="text-sm text-surface-300 mb-4">Already have a client and an agreement?</p><h2 className="text-3xl sm:text-4xl text-white">Give the work a clear starting point.</h2></div><Button href="/signup" size="lg" className="bg-white text-navy-900 hover:bg-surface-100 shrink-0">Create a TrustLink →</Button></div></section>
  </main><Footer/></>;
}
